### ISSUE TITLE
ZSH Not compatible: "resources/alacarte.sh: 31: declare: not found" and "resources/alacarte.sh: 291: Syntax error: word unexpected (expecting ")")"

### ISSUE THREAD

**Issue by pr0b3r7** [yassirlaaouissi/EZEA#1]
resources/alacarte.sh: 31: declare: not found
resources/alacarte.sh: 291: Syntax error: word unexpected (expecting ")")
appears on every window in tmux

<img width="818" alt="image" src="https://user-images.githubusercontent.com/14915771/113529593-d1f19880-9591-11eb-89b6-bf5ab7fa82f3.png">

**Comment by yassirlaaouissi** [comment]
Did you download the entire git repo, or only the runme.sh file?

**Comment by pr0b3r7** [comment]
Added the full repo with git clone and downloaded the dependencies from their respective repos as well

**Comment by yassirlaaouissi** [comment]
@pr0b3r7 I see you are running ZSH, I am running bash. You might want to try and insert `#!/bin/bash` on the top line of enum.sh. If that does not work please let me know.

Source: https://askubuntu.com/questions/28311/problem-with-bash-script-declare-not-found

**Comment by yassirlaaouissi** [comment]
@pr0b3r7 if the above does not work please run the script in the following manner:
```
>$ bash ./runme.sh
Please run as root
Usage: sudo ./runme.sh <IP-Address>
```
Because you are using Z-shell, bash does not apply. You have to run this script with bash. Therefore only this syntax will apply. I will edit the readme.md for more clarity. And TBH, kali uses ZSH as standard so thanks for this issue. 
If it works and you have no further questions, please feel free to close this issue.

**Comment by pr0b3r7** [comment]
@yassirlaaouissi - First, big thank you and God bless your good work with this project.
Second, thank you for the quick responses providing support to my error.

Running the script while having ZSH as default Shell does not work - 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/14915771/113578893-866ed700-95f1-11eb-9416-a2bb1ec10100.png"> Even attempting the syntax above (passing the script directly to BASH), I hypothesize it is because tmux still defaults to ZSH (system shell) giving the declare error.

I switched the ZSH to BASH using the following method:

To change your shell to BASH with chsh, run:
type -a bash # find path to bash #
chsh -s /bin/bash ## change bash to bash ##

Verify it:
grep "^${USER}" /etc/passwd

Reboot 
Ran .runme.sh with and without bash pre-pended and it worked. 

One last question I would have is: 

à la carte, when triggering dirsearch chokes on a command to pass to python3 
<img width="498" alt="image" src="https://user-images.githubusercontent.com/14915771/113579164-e796aa80-95f1-11eb-9515-bb31079d6ed5.png"> "python3 -u https://givenIP -e php,txt,html,asp

If you would like me to open a new ticket for the last item I understand, just let me know. Thank you!

**Comment by yassirlaaouissi** [comment]
Hey @pr0b3r7 thanks man!
I'll add the info about how to switch to bash in the readme.
About the Dirbuster issue, please create a new ticket to maintain clarity and uniformity for future users debugging their issues.
Thanks for you understanding m8!

**Comment by yassirlaaouissi** [comment]
Updated MD @pr0b3r7 https://github.com/yassirlaaouissi/EZEA/commit/5d0dab85a8e04ff70f06849db451bff20132f791

**Comment by yassirlaaouissi** [comment]
@pr0b3r7 script now natively supports ZSH thanks to @jjvdhoven, check this merge: https://github.com/yassirlaaouissi/EZEA/commit/aceac19ad93b81def426c5421a01e5316abca6f4
