### ISSUE TITLE
Tilix issue on Kali

### ISSUE THREAD

**Issue by reikairen** [yassirlaaouissi/EZEA#11]
sudo ./runme.sh 127.0.0.1
./runme.sh: line 10: dconf: command not found
sudo: tilix: command not found

Kali does not have Tilix in its official repos and trying to manually install it causes complicated issues related to environment variables. Is there a way to fix this to not require Tilix or a way to get Tilix to easily work in Kali?

**Comment by jasper-vdhoven** [comment]
Hi , could you give some further details regarding the issues you’re encountering (i.e. what version of Kali, etc)?  If you don’t want to use Tilix, which is the intended way, feel free to implement it yourself and send in a pull request to get it merged!

**Comment by reikairen** [comment]
Kali is 2022.2 / Rolling. I am not against using Tilux but it looks like a lot of people are having issues getting it to work in Kali.  I was just wondering if there was a trivial way to either get Tilux working or to otherwise modify EZEA. No sweat if this was ineffective feedback or poor quality question for you.

**Comment by yassirlaaouissi** [comment]
@reikairen EZEA was built on top of the fundamental functionalities of TILIX. So to make it work would take a big refactor.

If I were you, try to install tilix on kali. Back when I used this script that was not all to hard. If you encounter trouble woth that, fix it.
