### ISSUE TITLE
Dirsearch not working

### ISSUE THREAD

**Issue by pr0b3r7** [yassirlaaouissi/EZEA#2]
à la carte, when triggering dirsearch chokes on a command to pass to python3

![image](https://user-images.githubusercontent.com/14915771/113643461-5f93bd80-9650-11eb-825a-f5a49954b5e2.png)

image "python3 -u https://givenIP -e php,txt,html,asp

**Comment by yassirlaaouissi** [comment]
@pr0b3r7 just fixed it in https://github.com/yassirlaaouissi/EZEA/commit/24da1ad916b8a1e69d9a6e9bf57623364fb272d5
Please clone the repo again and run the following command:
`sudo python3 -m pip install -r resources/dirsearch/requirements.txt `

If it does not work let me know. If it does, please close this issue :+1:

**Comment by pr0b3r7** [comment]
Hi @yassirlaaouissi - thank you for the support so far - 
1st, tried git pull to update the repo and under dirsearch dir there is nothing 
2nd tried rm -rfv /opt/EZEA and git clone in /opt/ but getting the same lack of anything under dirsearch 
<img width="802" alt="image" src="https://user-images.githubusercontent.com/14915771/113720807-feee9a00-96bc-11eb-9b93-457201714ca5.png">

**Comment by yassirlaaouissi** [comment]
@pr0b3r7 its fixed, basicly I hate git sometimes. Clone the repo again and follow the steps as described in the readme. Fixed in: https://github.com/yassirlaaouissi/EZEA/commit/126ea986df01b90284ccd5cf5d46f83095ff96bd

Please let me know if it still does not work.

**Comment by pr0b3r7** [comment]
@yassirlaaouissi - I pray the Lord blesses your life everyday. You have made my day better today, it felt really cool to interact in this way (I have not contributed much to other repos) and you have been beyond attentive and kind. 
<img width="2040" alt="image" src="https://user-images.githubusercontent.com/14915771/113751790-47688080-96da-11eb-9bb3-bd84f39af689.png">
I think this is now working how you intended it when writing it. 
:)

Thank you!

**Comment by yassirlaaouissi** [comment]
@pr0b3r7 thanks m8, if you have any other recommendations/bug reports please let me know.
