### ISSUE TITLE
tee: results/<target-ip>/alacarte/nmap.txt No such file or directory (ocurring with other files too)

### ISSUE THREAD

**Issue by pr0b3r7** [yassirlaaouissi/EZEA#8]
![EZEA-error](https://user-images.githubusercontent.com/14915771/114257110-d2bc6d00-998b-11eb-9a3e-c06d47da1fe2.png)
git pull --rebase today after using the script successfully earlier and started receiving this error - haven't had time to review latest few commits in detail but figured to lyk

**Comment by yassirlaaouissi** [comment]
Imma test it tommorow if you dont mind, have some stuff to do today.

**Comment by yassirlaaouissi** [comment]
@pr0b3r7 in which folder did you start the tool, and how did you run it?

**Comment by yassirlaaouissi** [comment]
Hey @pr0b3r7 I think I have fixed it now in https://github.com/yassirlaaouissi/EZEA/commit/52a40924ac84f4f1e397cbc9ee9572f97f6cd4c4
Please pull this project again and test. Let me know if it still does not work. I am going to close this issue for now. If the issue still persists, feel free to reopen the issue.

Thanks again for being so active in the issues!

**Comment by pr0b3r7** [comment]
will test again and provide feedback - forgot to set a reminder for this- hope youre doing OK

**Comment by yassirlaaouissi** [comment]
@pr0b3r7 I am doing fine thank you. Hope youcare doing well as well. Lemme know id you encounter something odd
